openapi: 3.0.3
info:
  title: CampusCribs API
  version: 1.0.0

paths:
  /app/me:
    $ref: ./paths/me.yaml

  /app/cribs:
    $ref: ./paths/Cribs.yaml

  /app/community:
    $ref: ./paths/Community.yaml

  /app/individualcrib/{postId}:
    $ref: ./paths/IndividualCrib.yaml

  # /app/individualcommunity/{postId}:

  /app/profile/{username}:
    $ref: ./paths/profile.yaml

  /app/chats:
    $ref: ./paths/chats/Chats.yaml

  /app/chats/{username}:
    $ref: ./paths/chats/IndividualChat.yaml

  /app/chats/{username}/settings:
    $ref: ./paths/chats/ChatSettings.yaml
