openapi: 3.0.3
info:
  title: CampusCribs API
  version: 1.0.0

paths:
  /curated/cribs:
    $ref: ./paths/curated/curated.yaml

  /posts/{postId}:
    $ref: ./paths/posts/postsByPostId.yaml
  /posts/{username}/list:
    $ref: ./paths/posts/listPostsByUserName.yaml

  /profile/{username}:
    $ref: ./paths/profile/profileBaseByUsername.yaml
